import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@/components/Provider";
import { Toaster } from "react-hot-toast";

import Header from "@/components/layout/Header";
import Sidebar from "@/components/layout/Sidebar";
// import { Session } from "next-auth";
// import RegisterModal from "@/components/modals/RegisterModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const items = [
  { label: "Notifications", href: "/notifications", icon: "", auth: true },
  { label: "Profile", href: "/users/123", icon: "", auth: true },
  { label: "yep", href: "", icon: "", auth: true },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="dark:bg-slate_ct dark:text-white_ct">
        <Provider>
          <Toaster />
          <Header items={items} />
          <Sidebar
            items={items}
            // session={session}
          />
          {children}
        </Provider>
      </body>
    </html>
  );
}
