import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@/components/Provider";
// import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";

import Header from "@/components/layout/Header";
import RegisterModal from "@/components/modals/RegisterModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <SessionProvider session={pageProps.session}>
    <html lang="en" className="dark">
      <body className="dark:bg-slate_ct dark:text-white_ct">
        <Provider>
          <RegisterModal/>
          <Toaster/>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
    // </SessionProvider>
  );
}
